services:
  user-service:
    build:
      context: ./user-service
    container_name: user-service
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - microservice

  product-service:
    build:
      context: ./product-service
    container_name: product-service
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - microservice


  order-service:
    build:
      context: ./order-service
    container_name: order-service
    ports:
      - "3002:3002"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - microservice

  gateway-service:
    build:
      context: ./gateway-service
    container_name: gateway-service
    depends_on:
      - user-service
      - product-service
      - order-service
    ports:
      - "3003:3003"
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - microservice

networks:
  microservice:
    driver: bridge